[package]
name = "serializer"
version = "0.1.0"
authors = ["Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_json = "1.0"