[package]
name = "tokyio"
version = "0.1.0"
authors = ["Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.3"
libc = "0.2"
log = "0.4"
pretty_env_logger = "0.2"